export const COMMON_EXERCISES = [
  'Bench Press',
  'Incline Dumbbell Press',
  'Overhead Press',
  'Squat',
  'Front Squat',
  'Deadlift',
  'Romanian Deadlift',
  'Lat Pulldown',
  'Pull Up',
  'Barbell Row',
  'Dumbbell Row',
  'Lateral Raise',
  'Bicep Curl',
  'Tricep Pushdown',
  'Leg Press',
  'Leg Curl',
  'Leg Extension',
  'Hip Thrust',
  'Calf Raise',
  'Face Pull',
  'Cable Fly',
  'Dip',
] as const;

export const EXERCISE_ALIASES: Record<string, string> = {
  bench: 'Bench Press',
  'bench press': 'Bench Press',
  'incline dumbbell press': 'Incline Dumbbell Press',
  'incline db press': 'Incline Dumbbell Press',
  ohp: 'Overhead Press',
  'overhead press': 'Overhead Press',
  'shoulder press': 'Overhead Press',
  squat: 'Squat',
  squats: 'Squat',
  deadlift: 'Deadlift',
  deadlifts: 'Deadlift',
  rdl: 'Romanian Deadlift',
  'lat pulldown': 'Lat Pulldown',
  pulldown: 'Lat Pulldown',
  'pull up': 'Pull Up',
  'pull ups': 'Pull Up',
  'lateral raise': 'Lateral Raise',
  'lateral raises': 'Lateral Raise',
  'side raises': 'Lateral Raise',
};
