import type {FoodUnit} from '../types';

export interface CommonFood {
  name: string;
  aliases: string[];
  unit: FoodUnit;
  /** Nutrition per `perQuantity` of `unit`. */
  perQuantity: number;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
}

/**
 * Small local table for common logging. Values are typical estimates,
 * not lab assays. Saved user foods always take priority.
 */
export const COMMON_FOODS: CommonFood[] = [
  {
    name: 'Egg',
    aliases: ['eggs', 'whole egg', 'boiled egg'],
    unit: 'piece',
    perQuantity: 1,
    calories: 70,
    protein: 6,
    carbs: 0.5,
    fat: 5,
  },
  {
    name: 'Chicken thigh',
    aliases: ['chicken thighs', 'boneless chicken thigh', 'thigh'],
    unit: 'g',
    perQuantity: 100,
    calories: 177,
    protein: 22,
    carbs: 0,
    fat: 9,
  },
  {
    name: 'Chicken breast',
    aliases: ['chicken breasts', 'breast'],
    unit: 'g',
    perQuantity: 100,
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
  },
  {
    name: 'Sourdough',
    aliases: ['sourdough bread', 'sourdough slice', 'slices sourdough'],
    unit: 'slice',
    perQuantity: 1,
    calories: 95,
    protein: 4,
    carbs: 18,
    fat: 0.8,
  },
  {
    name: 'Whey protein',
    aliases: ['whey', 'protein powder', 'scoop of whey', 'protein scoop'],
    unit: 'scoop',
    perQuantity: 1,
    calories: 120,
    protein: 24,
    carbs: 3,
    fat: 1.5,
  },
  {
    name: 'Greek yogurt',
    aliases: ['skyr', 'greek yoghurt', 'yogurt'],
    unit: 'g',
    perQuantity: 100,
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
  },
  {
    name: 'Apple',
    aliases: ['apples'],
    unit: 'piece',
    perQuantity: 1,
    calories: 95,
    protein: 0.5,
    carbs: 25,
    fat: 0.3,
  },
  {
    name: 'Banana',
    aliases: ['bananas'],
    unit: 'piece',
    perQuantity: 1,
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fat: 0.4,
  },
  {
    name: 'Guava',
    aliases: ['guavas'],
    unit: 'piece',
    perQuantity: 1,
    calories: 68,
    protein: 2.6,
    carbs: 14,
    fat: 1,
  },
  {
    name: 'Tomato',
    aliases: ['tomatoes'],
    unit: 'piece',
    perQuantity: 1,
    calories: 22,
    protein: 1.1,
    carbs: 4.8,
    fat: 0.2,
  },
  {
    name: 'Oyster mushrooms',
    aliases: ['oyster mushroom', 'mushrooms'],
    unit: 'g',
    perQuantity: 100,
    calories: 33,
    protein: 3.3,
    carbs: 6.1,
    fat: 0.4,
  },
  {
    name: 'Olive oil',
    aliases: ['oil'],
    unit: 'tbsp',
    perQuantity: 1,
    calories: 119,
    protein: 0,
    carbs: 0,
    fat: 13.5,
  },
  {
    name: 'Rice, cooked',
    aliases: ['rice', 'white rice', 'bowl of rice'],
    unit: 'g',
    perQuantity: 100,
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
  },
  {
    name: 'Oats',
    aliases: ['oatmeal', 'rolled oats'],
    unit: 'g',
    perQuantity: 100,
    calories: 389,
    protein: 17,
    carbs: 66,
    fat: 7,
  },
  {
    name: 'Milk',
    aliases: ['whole milk'],
    unit: 'ml',
    perQuantity: 100,
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
  },
  {
    name: 'Almonds',
    aliases: ['almond'],
    unit: 'g',
    perQuantity: 100,
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
  },
  {
    name: 'Salmon',
    aliases: ['salmon fillet'],
    unit: 'g',
    perQuantity: 100,
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
  },
  {
    name: 'Broccoli',
    aliases: [],
    unit: 'g',
    perQuantity: 100,
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
  },
  {
    name: 'Peanut butter',
    aliases: ['pb'],
    unit: 'tbsp',
    perQuantity: 1,
    calories: 94,
    protein: 4,
    carbs: 3,
    fat: 8,
  },
  {
    name: 'Coffee',
    aliases: ['black coffee'],
    unit: 'cup',
    perQuantity: 1,
    calories: 2,
    protein: 0.3,
    carbs: 0,
    fat: 0,
  },
];
